### ISSUE TITLE
[ASK]

### ISSUE THREAD

**Issue by tryhrj** [kmanjari/hrms#27]
Hello,

How to make this project work?

**Comment by tryhrj** [comment]
If you dont mind, please teach me via Team Viewer, please. I really2 need this project.

Thanks before.

**Comment by kmanjari** [comment]
i have update the readme file of the project

**Comment by tryhrj** [comment]
i dont know nothing about laravel, thanks for helping. I will check your readme.

**Comment by tryhrj** [comment]
this project need database, right? where can i find your sql database?

**Comment by khanof89** [comment]
when you will run php artisan migrate it will create the required tables

**Comment by tryhrj** [comment]
wow, amazing. i never know it before. This is my first app, extreamly cool. any impact to other database on phpmysql?

**Comment by khanof89** [comment]
No, just configure the database configuration in config/database.php

**Comment by tryhrj** [comment]
after migration complete, what next, how to check this app work well?

**Comment by khanof89** [comment]
run php artisan db:seed

**Comment by tryhrj** [comment]
oke, I try.

**Comment by tryhrj** [comment]
Guys, i got this, please help me, http://prntscr.com/d6ycfv

**Comment by khanof89** [comment]
run php artisan key:generate

**Comment by tryhrj** [comment]
key artisan generate not working for me

**Comment by tryhrj** [comment]
please give the complete step by step

**Comment by kmanjari** [comment]
check if you have a .env file in the root folder of your project.If not,then create an empty .env file and run php artisan key:generate
