### ISSUE TITLE
Error while running php artisan migrate

### ISSUE THREAD

**Issue by phunashi** [kmanjari/hrms#31]
[Illuminate\Database\QueryException]                                                                                                     
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'hrmsdb.posts' doesn't exist (SQL: select count(*) as aggregate from `posts`)

  [PDOException]                                                                          
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'hrmsdb.posts' doesn't exist

**Comment by khanof89** [comment]
for the time being please comment from line 17 to 30 in app/Providers/ViewShareServiceProvider.php will fix this in next commit

**Comment by phunashi** [comment]
Again I am getting this error!

  [RuntimeException]                                                         
  No supported encrypter found. The cipher and / or key length are invalid.

**Comment by khanof89** [comment]
run 

> > php artisan key:generate

 from your terminal/command prompt you will get a key open you .env file and paste this key as value to APP_KEY

**Comment by nekromoff** [comment]
Same here. If I run `php artisan key:generate`, same error is given.

**Comment by khanof89** [comment]
Please see https://laravel.io/forum/06-09-2015-no-supported-encrypter-found-the-cipher-and-or-key-length-are-invalid

**Comment by nekromoff** [comment]
.env file is missing in your repository and that's why it fails.

copying .env file (and correcting details) from another Laravel install and everythign works fine.
