### ISSUE TITLE
php artisan migrate

### ISSUE THREAD

**Issue by cloudi32003** [kmanjari/hrms#36]
C:\xampp\htdocs\hrms>php artisan migrate
Migration table created successfully.
  [Illuminate\Database\QueryException]
  SQLSTATE[42000]: Syntax error or access violation: 1072 Key column 'client_
  id' doesn't exist in table (SQL: alter table `projects` add constraint `pro
  jects_client_id_foreign` foreign key (`client_id`) references `clients` (`i
  d`) on delete cascade)

  [PDOException]
  SQLSTATE[42000]: Syntax error or access violation: 1072 Key column 'client_
  id' doesn't exist in table

Why I'm not able to login after key the username and password. Please advise.

**Comment by khanof89** [comment]
Some other developer has been working on the project and looks like she has messed it big time, i have pushed more changes, kindly keep me posted

**Comment by cloudi32003** [comment]
Hi Shahrukh,

Thank you so much for the help. Everything to migrate and seed db.

When I login to public page with login if email@gmail.com and pwd: 123456
and it only brings to the same page. Please advise.

Best Regards,
Johnny Lee

**Comment by khanof89** [comment]
I have made necessary changes which now diaplay errors on the login page if any
