### ISSUE TITLE
php artisan migrate

### ISSUE THREAD

**Issue by Dunrar** [kmanjari/hrms#44]
When I run the php artisan migrate command, I get the following error: 

In Connection.php line 664:

  SQLSTATE[HY000] [1049] Unknown database 'hrms' (SQL: select * from information_schema.tables where table_schema = h
  rms and table_name = migrations)

In PDOConnection.php line 47:

  SQLSTATE[HY000] [1049] Unknown database 'hrms'

In PDOConnection.php line 43:

  SQLSTATE[HY000] [1049] Unknown database 'hrms'

**Comment by khanof89** [comment]
Please make sure you have a .env file in the root directory with the following constants 

APP_NAME=
APP_ENV=
APP_KEY=
APP_DEBUG=
APP_URL=

LOG_CHANNEL=

DB_CONNECTION=
DB_HOST=
DB_PORT=
DB_DATABASE=
DB_USERNAME=
DB_PASSWORD=

BROADCAST_DRIVER=
CACHE_DRIVER=
SESSION_DRIVER=
SESSION_LIFETIME=
QUEUE_DRIVER=

REDIS_HOST=
REDIS_PASSWORD=
REDIS_PORT=

MAIL_DRIVER=
MAIL_HOST=
MAIL_PORT=
MAIL_USERNAME=
MAIL_PASSWORD=
MAIL_ENCRYPTION=

PUSHER_APP_ID=
PUSHER_APP_KEY=
PUSHER_APP_SECRET=
PUSHER_APP_CLUSTER=mt1

MIX_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
MIX_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"


fill in the credentials as per your local setup, also make sure you have a database named hrms locally
