### ISSUE TITLE
No connection could be made because the target machine actively refused it

### ISSUE THREAD

**Issue by youcef-dz35** [kmanjari/hrms#53]
hello guys,
   After a cloned the code i run the composer install command the when I tried to run the migrate commande some database connection issues came up 
here they are:
SQLSTATE[HY000] [2002] No connection could be made because the target machine actively refused it.
   (SQL: select * from information_schema.tables where table_schema = hrms and table_name = migrations)

In PDOConnection.php line 47:

  SQLSTATE[HY000] [2002] No connection could be made because the target machine actively refused it.

In PDOConnection.php line 43:

  SQLSTATE[HY000] [2002] No connection could be made because the target machine actively refused it.
I'm a newbie in laravel please help!

**Comment by khanof89** [comment]
You should have mysql running on your computer
